[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

gas_reports = ["TodoList"]
solc_version = '0.8.23'
evm_version = 'shanghai'

[rpc_endpoints]
h_testnet = "https://testnet.hashio.io/api"
h_mainnet = "https://mainnet.hashio.io/api"

# See more config options: https://book.getfoundry.sh/config/, https://book.getfoundry.sh/reference/config/
